title:   # You can add your name here

# description: Software Engineer with expereince in Development, Testing & Automation for 13 years

# show_downloads: true # Fix spelling

# theme: jekyll-theme-minimal 
markdown: kramdown
# plugins:
  - jekyll-seo-tag # Add SEO plugin

# email: shivang.koshti@yahoo.com # Allow visitors to contact you

